In [205]:
# imports standard
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import cross_val_score, train_test_split, GridSearchCV

# imports added after
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier

In [5]:
# read in the set
df = pd.read_csv('./datasets/2018nycsquirrel.csv')

In [73]:
# check head and columns
print(df.columns)
df.head(15)

Index(['X', 'Y', 'Unique Squirrel ID', 'Hectare', 'Shift', 'Date',
       'Hectare Squirrel Number', 'Age', 'Primary Fur Color',
       'Highlight Fur Color', 'Combination of Primary and Highlight Color',
       'Color notes', 'Location', 'Above Ground Sighter Measurement',
       'Specific Location', 'Running', 'Chasing', 'Climbing', 'Eating',
       'Foraging', 'Other Activities', 'Kuks', 'Quaas', 'Moans', 'Tail flags',
       'Tail twitches', 'Approaches', 'Indifferent', 'Runs from',
       'Other Interactions', 'Lat/Long', 'Zip Codes', 'Community Districts',
       'Borough Boundaries', 'City Council Districts', 'Police Precincts'],
      dtype='object')

,X,Y,Unique Squirrel ID,Hectare,Shift,Date,Hectare Squirrel Number,Age,Primary Fur Color,Highlight Fur Color,...,Approaches,Indifferent,Runs from,Other Interactions,Lat/Long,Zip Codes,Community Districts,Borough Boundaries,City Council Districts,Police Precincts
0,-73.956134,40.794082,37F-PM-1014-03,37F,PM,10142018,3,NaN,NaN,NaN,...,False,False,False,NaN,POINT (-73.9561344937861 40.7940823884086),NaN,19,4,19,13
1,-73.957044,40.794851,37E-PM-1006-03,37E,PM,10062018,3,Adult,Gray,Cinnamon,...,False,False,True,me,POINT (-73.9570437717691 40.794850940803904),NaN,19,4,19,13
2,-73.976831,40.766718,2E-AM-1010-03,02E,AM,10102018,3,Adult,Cinnamon,NaN,...,False,True,False,NaN,POINT (-73.9768311751004 40.76671780725581),NaN,19,4,19,13
3,-73.975725,40.769703,5D-PM-1018-05,05D,PM,10182018,5,Juvenile,Gray,NaN,...,False,False,True,NaN,POINT (-73.9757249834141 40.7697032606755),NaN,19,4,19,13
4,-73.959313,40.797533,39B-AM-1018-01,39B,AM,10182018,1,NaN,NaN,NaN,...,False,False,False,NaN,POINT (-73.9593126695714 40.797533370163),NaN,19,4,19,13
5,-73.956570,40.790256,33H-AM-1019-02,33H,AM,10192018,2,Juvenile,Gray,Cinnamon,...,False,False,False,NaN,POINT (-73.9565700386162 40.7902561000937),NaN,19,4,19,13
6,-73.971974,40.769305,6G-PM-1020-02,06G,PM,10202018,2,Adult,Gray,NaN,...,False,True,False,NaN,POINT (-73.9719735582476 40.7693045133578),NaN,19,4,19,13
7,-73.960261,40.794288,35C-PM-1013-03,35C,PM,10132018,3,NaN,Gray,Cinnamon,...,False,False,True,NaN,POINT (-73.9602609920814 40.79428830455661),NaN,19,4,19,13
8,-73.977072,40.772975,7B-AM-1008-09,07B,AM,10082018,9,Adult,Gray,NaN,...,False,True,False,NaN,POINT (-73.9770718586754 40.7729752391435),NaN,19,4,19,13
9,-73.959641,40.790313,32E-PM-1017-14,32E,PM,10172018,14,Adult,Gray,NaN,...,False,False,True,NaN,POINT (-73.9596413903948 40.7903128889029),NaN,19,4,19,13
10,-73.970268,40.776213,13E-AM-1017-05,13E,AM,10172018,5,Adult,Gray,Cinnamon,...,False,False,False,NaN,POINT (-73.9702676472613 40.7762126854894),NaN,19,4,19,13
11,-73.968361,40.772591,11H-AM-1010-03,11H,AM,10102018,3,Adult,Cinnamon,White,...,False,True,False,NaN,POINT (-73.9683613516225 40.7725908847499),NaN,19,4,19,13
12,-73.954120,40.793181,36H-AM-1010-02,36H,AM,10102018,2,Adult,Gray,NaN,...,False,False,False,NaN,POINT (-73.9541201789795 40.7931811701082),NaN,19,4,19,13
13,-73.958269,40.791737,33F-AM-1008-02,33F,AM,10082018,2,Adult,Gray,NaN,...,False,True,False,NaN,POINT (-73.9582694312289 40.7917367820255),NaN,19,4,19,13
14,-73.967429,40.782972,21C-PM-1006-01,21C,PM,10062018,1,Adult,Gray,NaN,...,False,False,False,NaN,POINT (-73.9674285955293 40.7829723919744),NaN,19,4,19,13

In [7]:
# verify data types
df.dtypes

X                                             float64
Y                                             float64
Unique Squirrel ID                             object
Hectare                                        object
Shift                                          object
Date                                            int64
Hectare Squirrel Number                         int64
Age                                            object
Primary Fur Color                              object
Highlight Fur Color                            object
Combination of Primary and Highlight Color     object
Color notes                                    object
Location                                       object
Above Ground Sighter Measurement               object
Specific Location                              object
Running                                          bool
Chasing                                          bool
Climbing                                         bool
Eating                                           bool
Foraging                                         bool
Other Activities                               object
Kuks                                             bool
Quaas                                            bool
Moans                                            bool
Tail flags                                       bool
Tail twitches                                    bool
Approaches                                       bool
Indifferent                                      bool
Runs from                                        bool
Other Interactions                             object
Lat/Long                                       object
Zip Codes                                     float64
Community Districts                             int64
Borough Boundaries                              int64
City Council Districts                          int64
Police Precincts                                int64
dtype: object

In [8]:
df.isna().sum()

X                                                0
Y                                                0
Unique Squirrel ID                               0
Hectare                                          0
Shift                                            0
Date                                             0
Hectare Squirrel Number                          0
Age                                            121
Primary Fur Color                               55
Highlight Fur Color                           1086
Combination of Primary and Highlight Color       0
Color notes                                   2841
Location                                        64
Above Ground Sighter Measurement               114
Specific Location                             2547
Running                                          0
Chasing                                          0
Climbing                                         0
Eating                                           0
Foraging                                         0
Other Activities                              2586
Kuks                                             0
Quaas                                            0
Moans                                            0
Tail flags                                       0
Tail twitches                                    0
Approaches                                       0
Indifferent                                      0
Runs from                                        0
Other Interactions                            2783
Lat/Long                                         0
Zip Codes                                     3014
Community Districts                              0
Borough Boundaries                               0
City Council Districts                           0
Police Precincts                                 0
dtype: int64

`Hectare` - May keep, classifier <br>
`Combination of Primary and Highlight Color` - redundant<br>
`Color notes` - spase, too many nulls and context required<br>
`Above Ground Sighter Measurement` - contextual, sparse, unneeded <br>
`Specific Location` - unnecessary notes, sparase<br>
`Other Activities` - unnecessary notes, sparase<br>
`Other Interactions` - unnecessary notes, sparse** may keep <br>
`Lat/Long` - compare to X, Y<br>
`Zip Codes` - too many nulls<br>
`Highlight Fur Color` - Subjective to lighting and has too many values for cleaning
`Community Districts`, `Borough Boundaries`, `City Council Districts`, `Police Precincts` - all same value <br>

In [72]:
# function cleaners

In [68]:
def val(dataframe, cols):
    for col in dataframe[cols].columns:
        print(f'{col} count: \n{dataframe[col].value_counts(normalize=True)}')

In [74]:
def val(dataframe, cols):
    for col in dataframe[cols].columns:
        print(f'{col} count: \n{dataframe[col].value_counts(normalize=True)}')

In [75]:
def full_val(df):
    for col in df.columns:
        print(f'{col} count: \n{df[col].value_counts(normalize=True)}')

In [69]:
#clean the column names to lower case without spaces
def clean_col(data):
    name = {}
    for column in data.columns:
        name[column] = column.lower().replace(' ', '_')
    return data.rename(columns = name, inplace = True)

#from richard ling DSI-11 project 2

In [84]:
def df_stats(df): 
    tempdf = pd.DataFrame()
    tempdf['dtype'] = df.dtypes
    tempdf['nulls'] = df.isna().sum()
    tempdf['base/mean'] = df.mean()
#    tempdf['total categories'] = df.value_counts().sum() ## not working, need to mask a function and run inside
    tempdf['uniques'] = df.nunique()
    return tempdf
# Colin Simon/Matt Burke DSI-11 project 2

In [85]:
# data dictionary
## https://data.cityofnewyork.us/Environment/2018-Central-Park-Squirrel-Census-Squirrel-Data/vfnx-vebw

In [86]:
df_stats(df)

,dtype,nulls,base/mean,uniques
X,float64,0,-7.396718e+01,3023
Y,float64,0,4.078085e+01,3023
Unique Squirrel ID,object,0,NaN,3018
Hectare,object,0,NaN,339
Shift,object,0,NaN,2
Date,int64,0,1.011949e+07,11
Hectare Squirrel Number,int64,0,4.123718e+00,23
Age,object,121,NaN,3
Primary Fur Color,object,55,NaN,3
Highlight Fur Color,object,1086,NaN,10
Combination of Primary and Highlight Color,object,0,NaN,22
Color notes,object,2841,NaN,135
Location,object,64,NaN,2
Above Ground Sighter Measurement,object,114,NaN,41
Specific Location,object,2547,NaN,304
Running,bool,0,2.414820e-01,2
Chasing,bool,0,9.229242e-02,2
Climbing,bool,0,2.176646e-01,2
Eating,bool,0,2.514059e-01,2
Foraging,bool,0,4.746940e-01,2
Other Activities,object,2586,NaN,307
Kuks,bool,0,3.374132e-02,2
Quaas,bool,0,1.653986e-02,2
Moans,bool,0,9.923917e-04,2
Tail flags,bool,0,5.127357e-02,2
Tail twitches,bool,0,1.435660e-01,2
Approaches,bool,0,5.888191e-02,2
Indifferent,bool,0,4.809792e-01,2
Runs from,bool,0,2.242805e-01,2
Other Interactions,object,2783,NaN,197
Lat/Long,object,0,NaN,3023
Zip Codes,float64,3014,1.182822e+04,4
Community Districts,int64,0,1.899603e+01,5
Borough Boundaries,int64,0,4.000000e+00,1
City Council Districts,int64,0,1.907046e+01,3
Police Precincts,int64,0,1.300463e+01,5

In [ ]:
cols_of_interest = ['Police Precincts', 'City Council Districts', 'Borough Boundaries', 'Community Districts']

In [66]:
cols_nulls = ['Zip Codes', 'Other Interactions', 'Other Activities', 'Specific Location']

In [122]:
full_val(squirreldf)

x count:
-73.960883    0.000331
-73.967759    0.000331
-73.967762    0.000331
-73.970551    0.000331
-73.965328    0.000331
                ...
-73.953287    0.000331
-73.971758    0.000331
-73.958968    0.000331
-73.977216    0.000331
-73.961565    0.000331
Name: x, Length: 3023, dtype: float64
y count:
40.791156    0.000331
40.773239    0.000331
40.766558    0.000331
40.778528    0.000331
40.775645    0.000331
               ...
40.788576    0.000331
40.766860    0.000331
40.779008    0.000331
40.771771    0.000331
40.766095    0.000331
Name: y, Length: 3023, dtype: float64
unique_squirrel_id count:
4C-PM-1010-05     0.000662
7D-PM-1010-01     0.000662
1F-AM-1010-04     0.000662
40B-AM-1019-06    0.000662
37E-PM-1006-03    0.000662
                    ...
15F-PM-1010-04    0.000331
37G-PM-1007-06    0.000331
29A-PM-1019-01    0.000331
16A-PM-1019-07    0.000331
7E-PM-1013-03     0.000331
Name: unique_squirrel_id, Length: 3018, dtype: float64
shift count:
PM    0.554416
AM    0.445584
Name: shift, dtype: float64
date count:
10132018    0.143566
10072018    0.133973
10142018    0.121733
10062018    0.111479
10102018    0.110817
10082018    0.094277
10122018    0.072114
10172018    0.071452
10182018    0.066159
10192018    0.052266
10202018    0.022163
Name: date, dtype: float64
primary_fur_color count:
Gray        0.833221
Cinnamon    0.132075
Black       0.034704
Name: primary_fur_color, dtype: float64
location count:
Ground Plane    0.715106
Above Ground    0.284894
Name: location, dtype: float64
running count:
0    0.758518
1    0.241482
Name: running, dtype: float64
chasing count:
0    0.907708
1    0.092292
Name: chasing, dtype: float64
climbing count:
0    0.782335
1    0.217665
Name: climbing, dtype: float64
foraging count:
0    0.525306
1    0.474694
Name: foraging, dtype: float64
kuks count:
0    0.966259
1    0.033741
Name: kuks, dtype: float64
quaas count:
0    0.98346
1    0.01654
Name: quaas, dtype: float64
moans count:
0    0.999008
1    0.000992
Name: moans, dtype: float64
tail_flags count:
0    0.948726
1    0.051274
Name: tail_flags, dtype: float64
tail_twitches count:
0    0.856434
1    0.143566
Name: tail_twitches, dtype: float64
approaches count:
0    0.941118
1    0.058882
Name: approaches, dtype: float64
indifferent count:
0    0.519021
1    0.480979
Name: indifferent, dtype: float64
runs_from count:
0    0.775719
1    0.224281
Name: runs_from, dtype: float64

In [61]:
# verify columns of interest
val(df, cols_of_interest)

Police Precincts count:
13    0.996692
18    0.001654
11    0.000662
10    0.000662
12    0.000331
Name: Police Precincts, dtype: float64
City Council Districts count:
19    0.997023
36    0.001654
51    0.001323
Name: City Council Districts, dtype: float64
Borough Boundaries count:
4    1.0
Name: Borough Boundaries, dtype: float64
Community Districts count:
19    0.996692
18    0.001654
23    0.000662
11    0.000662
20    0.000331
Name: Community Districts, dtype: float64

In [87]:
clean_col(df)
df.columns

Index(['x', 'y', 'unique_squirrel_id', 'hectare', 'shift', 'date',
       'hectare_squirrel_number', 'age', 'primary_fur_color',
       'highlight_fur_color', 'combination_of_primary_and_highlight_color',
       'color_notes', 'location', 'above_ground_sighter_measurement',
       'specific_location', 'running', 'chasing', 'climbing', 'eating',
       'foraging', 'other_activities', 'kuks', 'quaas', 'moans', 'tail_flags',
       'tail_twitches', 'approaches', 'indifferent', 'runs_from',
       'other_interactions', 'lat/long', 'zip_codes', 'community_districts',
       'borough_boundaries', 'city_council_districts', 'police_precincts'],
      dtype='object')

In [145]:
# select columns of interest again
# extra features useful for consideration in our model
## we will convert, dummy, and remove as necessary
features = ['x', 'y', 'lat/long', 'unique_squirrel_id','shift', 'date', 'primary_fur_color', 'location']


# boolean features of squirrel actions, the core of our model
## convert to boolean, confirm val-counts
actioncols = ['running', 'chasing', 'climbing', 'foraging', 'kuks', 'quaas', 'moans', 'tail_flags', 'tail_twitches', 'approaches', 'indifferent']

# will the squirrel run from us?
## same as actioncols
target = ['runs_from']

# full columns set
total_cols = ['x', 'y', 'lat/long', 'unique_squirrel_id','shift', 'date', 'primary_fur_color', 'location', 'running', 'chasing', 'climbing', 'foraging', 'kuks', 'quaas', 'moans', 'tail_flags', 'tail_twitches', 'approaches', 'indifferent', 'runs_from']

In [146]:
squirreldf = df[total_cols]

In [147]:
df_stats(squirreldf)

                      dtype  nulls     base/mean  uniques
x                   float64      0 -7.396718e+01     3023
y                   float64      0  4.078085e+01     3023
lat/long             object      0           NaN     3023
unique_squirrel_id   object      0           NaN     3018
shift                object      0           NaN        2
date                  int64      0  1.011949e+07       11
primary_fur_color    object     55           NaN        3
location             object     64           NaN        2
running                bool      0  2.414820e-01        2
chasing                bool      0  9.229242e-02        2
climbing               bool      0  2.176646e-01        2
foraging               bool      0  4.746940e-01        2
kuks                   bool      0  3.374132e-02        2
quaas                  bool      0  1.653986e-02        2
moans                  bool      0  9.923917e-04        2
tail_flags             bool      0  5.127357e-02        2
tail_twitches          bool      0  1.435660e-01        2
approaches             bool      0  5.888191e-02        2
indifferent            bool      0  4.809792e-01        2
runs_from              bool      0  2.242805e-01        2

In [148]:
# I'm ok with just dropping the NaN rows if we have 3000+ rows of data.
squirreldf.shape

(3023, 20)

In [149]:
# delete unnecessary columns
squirreldf.dropna(inplace=True)

/Users/yvir/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [150]:
#confirm clean set
squirreldf.isna().sum()

x                     0
y                     0
lat/long              0
unique_squirrel_id    0
shift                 0
date                  0
primary_fur_color     0
location              0
running               0
chasing               0
climbing              0
foraging              0
kuks                  0
quaas                 0
moans                 0
tail_flags            0
tail_twitches         0
approaches            0
indifferent           0
runs_from             0
dtype: int64

In [104]:
val(df, ['primary_fur_color', 'location'])

primary_fur_color count:
Gray        0.833221
Cinnamon    0.132075
Black       0.034704
Name: primary_fur_color, dtype: float64
location count:
Ground Plane    0.715106
Above Ground    0.284894
Name: location, dtype: float64

In [151]:
# convert action features
squirreldf[actioncols] = squirreldf[actioncols].astype(int)

/Users/yvir/opt/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py:2963: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

In [152]:
# convert target
squirreldf['runs_from'] = squirreldf['runs_from'].astype(int)

/Users/yvir/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [153]:
squirreldf['date'] #checking date format for conversion

1       10062018
2       10102018
3       10182018
5       10192018
6       10202018
          ...
3018    10072018
3019    10132018
3020    10122018
3021    10102018
3022    10122018
Name: date, Length: 2919, dtype: int64

In [155]:
# convert date to datetime format
squirreldf['date'] = pd.to_datetime(squirreldf['date'], format='%m%d%Y')
squirreldf['date'].head(2)
# %m = month 
# %d = day
# %Y = Year with century as decimal format (0001 instead of 1)
## ultimately we will not use this feature as it only spans a week of the year observed

/Users/yvir/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

1   2018-10-06
2   2018-10-10
Name: date, dtype: datetime64[ns]

In [164]:
squirreldf[['x', 'y', 'lat/long']].head(2)

           x          y                                      lat/long
1 -73.957044  40.794851  POINT (-73.9570437717691 40.794850940803904)
2 -73.976831  40.766718   POINT (-73.9768311751004 40.76671780725581)

In [178]:
import geopandas as gpd
from shapely import wkt
squirreldf['lat/long'] = squirreldf['lat/long'].apply(wkt.loads)

/Users/yvir/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [179]:
gdf = gpd.GeoDataFrame(squirreldf.drop(['x','y'], axis = 1), geometry = 'lat/long')

In [183]:
gdf.head()

#our goal from here would be to separate each coordinate zone into North, South, East, West,
## then apply dummy columns, we'll leave the gdf for plotting options later

,lat/long,unique_squirrel_id,shift,date,primary_fur_color,location,running,chasing,climbing,foraging,kuks,quaas,moans,tail_flags,tail_twitches,approaches,indifferent,runs_from
1,POINT (-73.95704 40.79485),37E-PM-1006-03,PM,2018-10-06,Gray,Ground Plane,1,0,0,0,0,0,0,0,0,0,0,1
2,POINT (-73.97683 40.76672),2E-AM-1010-03,AM,2018-10-10,Cinnamon,Above Ground,0,0,1,0,0,0,0,0,0,0,1,0
3,POINT (-73.97572 40.76970),5D-PM-1018-05,PM,2018-10-18,Gray,Above Ground,0,0,1,0,0,0,0,0,0,0,0,1
5,POINT (-73.95657 40.79026),33H-AM-1019-02,AM,2018-10-19,Gray,Ground Plane,0,0,0,0,0,0,0,0,0,0,0,0
6,POINT (-73.97197 40.76930),6G-PM-1020-02,PM,2018-10-20,Gray,Ground Plane,1,1,0,0,0,0,0,0,0,0,1,0

In [182]:
gdf['runs_from'].value_counts()

0    2255
1     664
Name: runs_from, dtype: int64

In [187]:
squirreldf[features]
# our final three features for cleaning: fur color, location, and shift

,x,y,lat/long,unique_squirrel_id,shift,date,primary_fur_color,location
1,-73.957044,40.794851,POINT (-73.95704377176909 40.7948509408039),37E-PM-1006-03,PM,2018-10-06,Gray,Ground Plane
2,-73.976831,40.766718,POINT (-73.9768311751004 40.76671780725581),2E-AM-1010-03,AM,2018-10-10,Cinnamon,Above Ground
3,-73.975725,40.769703,POINT (-73.9757249834141 40.7697032606755),5D-PM-1018-05,PM,2018-10-18,Gray,Above Ground
5,-73.956570,40.790256,POINT (-73.95657003861621 40.7902561000937),33H-AM-1019-02,AM,2018-10-19,Gray,Ground Plane
6,-73.971974,40.769305,POINT (-73.9719735582476 40.7693045133578),6G-PM-1020-02,PM,2018-10-20,Gray,Ground Plane
...,...,...,...,...,...,...,...,...
3018,-73.963943,40.790868,POINT (-73.9639431360458 40.7908677445466),30B-AM-1007-04,AM,2018-10-07,Gray,Ground Plane
3019,-73.970402,40.782560,POINT (-73.9704015859639 40.7825600069973),19A-PM-1013-05,PM,2018-10-13,Gray,Ground Plane
3020,-73.966587,40.783678,POINT (-73.96658719935169 40.7836775064883),22D-PM-1012-07,PM,2018-10-12,Gray,Ground Plane
3021,-73.963994,40.789915,POINT (-73.9639941227864 40.7899152327912),29B-PM-1010-02,PM,2018-10-10,Gray,Ground Plane
3022,-73.975479,40.769640,POINT (-73.97547941915531 40.7696404489025),5E-PM-1012-01,PM,2018-10-12,Cinnamon,Ground Plane

In [190]:
val(squirreldf, ['primary_fur_color', 'location', 'shift'])

primary_fur_color count:
Gray        0.833847
Cinnamon    0.130867
Black       0.035286
Name: primary_fur_color, dtype: float64
location count:
Ground Plane    0.722508
Above Ground    0.277492
Name: location, dtype: float64
shift count:
PM    0.553957
AM    0.446043
Name: shift, dtype: float64

In [192]:
# fur color - 3 categories
fur_dummies = pd.get_dummies(squirreldf['primary_fur_color'].str.lower(), prefix = 'fur', drop_first = True)
squirreldf.drop(columns = ['primary_fur_color'], inplace=True)

# location - boolean
squirreldf['on_ground'] = squirreldf['location'].str.lower().map({
    'ground plane' : 1,
    'above ground' : 0,
})

# shift - boolean 
squirreldf['is_morning'] = squirreldf['shift'].str.lower().map({
    'am' : 1,
    'pm' : 0,
})

/Users/yvir/opt/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py:3997: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,
/Users/yvir/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
/Users/yvir/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  from ipykernel import kernelapp as app

In [195]:
squirreldf.columns

Index(['x', 'y', 'lat/long', 'unique_squirrel_id', 'shift', 'date', 'location',
       'running', 'chasing', 'climbing', 'foraging', 'kuks', 'quaas', 'moans',
       'tail_flags', 'tail_twitches', 'approaches', 'indifferent', 'runs_from',
       'on_ground', 'is_morning'],
      dtype='object')

In [197]:
# join our dummies
squirreldf = squirreldf.join(fur_dummies, on = squirreldf.index)

In [198]:
squirrel_model = squirreldf.drop(columns = ['x','y','lat/long', 'unique_squirrel_id', 'shift', 'date', 'location'])
squirrel_model.columns

Index(['running', 'chasing', 'climbing', 'foraging', 'kuks', 'quaas', 'moans',
       'tail_flags', 'tail_twitches', 'approaches', 'indifferent', 'runs_from',
       'on_ground', 'is_morning', 'fur_cinnamon', 'fur_gray'],
      dtype='object')

In [199]:
squirrel_model['runs_from'].value_counts()

0    2255
1     664
Name: runs_from, dtype: int64

In [ ]:
#randomly samples android gaming posts to match number of iosgaming posts 
droid_df = traindf[traindf['is_iosgaming']==0].sample(n = traindf.is_iosgaming.value_counts()[1], replace = False, random_state = 42)

In [200]:
# now that we have our model-ready dataframe, let's set up equal categorical samples, we'll do 500 each.
abovedf = squirrel_model[squirrel_model['runs_from'] == 1].sample(n = 500, replace = False, random_state = 42)
belowdf = squirrel_model[squirrel_model['runs_from'] == 0].sample(n = 500, replace = False, random_state = 42)
modeldf = pd.concat([abovedf, belowdf], axis = 0)

In [204]:
X = modeldf.drop(columns='runs_from')
y = modeldf['runs_from']
print(X.shape) # feature set
print(y.shape) # target
print(modeldf['runs_from'].value_counts())

(1000, 15)
(1000,)
1    500
0    500
Name: runs_from, dtype: int64

In [208]:
# train test split our data
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 42) #we'll leave the defaul 75/25 split

In [206]:
# 2 models regular LR and KNN
lr = LogisticRegression(solver = 'lbfgs', penalty = 'none')
knn = KNeighborsClassifier(n_neighbors=3, p = 2)

In [209]:
lr.fit(X_train, y_train)
print(f' Training Score: {lr.score(X_train, y_train)}')
print(f'Testing Score: {lr.score(X_test, y_test)}')

 Training Score: 0.812
Testing Score: 0.812

In [210]:
knn.fit(X_train, y_train)
print(f' Training Score: {knn.score(X_train, y_train)}')
print(f'Testing Score: {knn.score(X_test, y_test)}')

 Training Score: 0.7466666666666667
Testing Score: 0.66

In [211]:
modeldf.to_csv('./datasets/squirrel_dataframe.csv', index = False)

In [ ]:
## next we set up pipes and hyper params, otherwise we explore our findings

In [ ]:
### initial thoughts
# can capture squirrel locations

## uses
# identify squirrel based off characteristics
# set up expectations based of squirrel
# extra squirrel facts (use noise they were making and reaction to human as an exploratory talking point)